apps:
  - name: "App1"
    target_url: "https://test-app-1-delta.vercel.app/"
  - name: "Produzione"
    target_url: "https://claude.ai/public/artifacts/ca03e490-0100-499e-a14d-fdca3e96a1a5"
  - name: "Costo Orario"
    target_url: "https://claude.ai/public/artifacts/ca03e490-0100-499e-a14d-fdca3e96a1a5"
  - name: "Agenda Produttiva"
    target_url: "https://g.co/gemini/share/c3a5e143ab0d"